### ISSUE TITLE
关于内存使用量的问题

### ISSUE THREAD

**Issue by shenbaise** [CastellanZhang/alphaFM#10]
这个项目还维护吗？代码存在严重的内存泄漏问题，虽然我不懂C++，但看了下代码貌似没有释放内存的代码。
训练模型的过程中内存不断上涨，训练了17亿条样本的时候内存已经涨到近80%，100G了。

              total        used        free      shared  buff/cache   available
Mem:           125G        101G        6.2G        8.0M         18G         18G

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
22797 algorit+  20   0  0.098t 0.097t   1544 S  50.2 79.4   1280:04 fm_train

**Comment by CastellanZhang** [comment]
代码中所有new的内存都是模型参数相关的，这些内存在整个训练过程不能释放，所以偷懒没有写释放的代码，因为训练结束进程退出自然释放。
内存不断上涨是正常的，因为新的样本不断读进来，特征维度会越来越大，存储模型参数需要的内存也越来越大。样本不会常驻内存，每条过一遍就都释放了。
你的内存占了100G，一方面可能是你的特征维度过高，一方面可能是你的-dim参数的k2过大，即向量v的维度过大。如果内存不够，需要你控制一下你的特征维度或者把k2参数调小一点。

**Comment by CastellanZhang** [comment]
干掉L2没什么用。调大L1正则即可，效果损失要自己做实验，数据不同结论不同，没法互相参考。
