### ISSUE TITLE
在线训练时，载入模型后，卡在 start！ init end！上，并不开始模型训练 

### ISSUE THREAD

**Issue by lcshr123** [CastellanZhang/alphaFM#19]
以下是我的训练输出，从 2:40：45 输出  init end! 之后，八个小时都未开始训练。 机器有 40 个核， 用 13 个线程肯定没问题用 top 命令看了内存使用情况，没有其他使用内存的大程序。这种情况会有哪些可能的原因呢？
`the train command is :     hadoop fs -cat hdfs://xxxxx/20190124/22/* |   /home/stat/alphaFM/bin/fm_train  -imf txt -im  model_test.txt  -init_stdev 0 -core 13 -w_l1 9.91 -w_alpha  0.01  -dim 1,1,0  -mf txt -m model_test.txt 
load model...
model loading finished
[2019-01-25 02:40:45] start!
[2019-01-25 02:40:45] init end!`

**Comment by CastellanZhang** [comment]
start!和init end!是怎么来的？我代码里好像没有输出这两个字符串吧？
你可以把hdfs上的样本先下载一部分到本地试试，看看能不能跑起来。

**Comment by lcshr123** [comment]
> start!和init end!是怎么来的？我代码里好像没有输出这两个字符串吧？
> 你可以把hdfs上的样本先下载一部分到本地试试，看看能不能跑起来。

下载到本地也跑不起来。。   您觉得可以从哪些方面分析原因呢？

start!和init end! 应该是自动输出的，我这边没有改动源码呀
