### ISSUE TITLE
predict文件的label是如何确定的？

### ISSUE THREAD

**Issue by JyiHUO** [CastellanZhang/alphaFM#22]
![image](https://user-images.githubusercontent.com/16526817/57209790-7a94c780-700c-11e9-9e73-1b606f2f9449.png)

你好，我使用fm_predict输出了label 和 概率，我原本以为label = 1是当score > 0.5。但根据输出的结果来看似乎不是这样的，请问输出文件的label是如何确定的？

**Comment by Mecca-273** [comment]
请问你这个问题解决了吗？我看代码里写的label是输入样本中的label, 但实际输出的并不是啊😅
