### ISSUE TITLE
我想请教一下为什么我用alphaFM跑出来的结果auc表现远不如LR

### ISSUE THREAD

**Issue by fooSynaptic** [CastellanZhang/alphaFM#29]
在预测文件中，第一个是label`1/-1`，后面跟着的是概率，在计算auc的时候，我通过如下的方式来获取模型预测的概率
- 如果label是1（在`fm_pre.txt`文件中），那么模型预测为1的概率为prob
- 如果label是-1，那么模型预测为1 的概率为1-prob

如上准备的概率和标签一起进入`BinaryClassificationMetrics`，最后表现的auc不超过1%，而LR接近90%，请问可能在哪里出现了问题？

**Comment by caomeibaobao1994** [comment]
我理解，不管label是什么，模型预测为1的概率都是prob

**Comment by fooSynaptic** [comment]
i found fm version run correctly, closed.
